Add mayhem support
mayhemheroes/capstone-rs pull request #1
Opened 2022-05-16 03:02 UTC by WGibbs15

2022-06-15 03:23 UTC, xansec requested changes
Please make the requested changes.

2022-06-15 03:23 UTC, xansec commented on Mayhemfile
> +project: wgibbs15/capstone-rs-mayhem
Please use generic project names.

2022-06-15 03:23 UTC, xansec commented on capstone-rs/fuzz/fuzz_targets/fuzz_target_disasm_x86_64.rs
>          let detail: InsnDetail = cs.insn_detail(&i).unwrap();
Can you explain this change?

2022-06-16 05:49 UTC, WGibbs15 commented on capstone-rs/fuzz/fuzz_targets/fuzz_target_disasm_x86_64.rs
>          let detail: InsnDetail = cs.insn_detail(&i).unwrap();
This file wasn't touched for years, but Capstone updated to a newer version and changed some function return values.

2022-06-21 18:46 UTC, xansec commented on capstone-rs/fuzz/fuzz_targets/fuzz_target_disasm_x86_64.rs
>          let detail: InsnDetail = cs.insn_detail(&i).unwrap();
Gotcha, thanks!

2022-06-21 18:46 UTC, merged